### ISSUE TITLE
Does matchicons.lua need dirx?

### ISSUE THREAD

**Issue by NewUserHa** [chrisant996/clink-gizmos#14]
`matchicons.lua`
after spending more than 30 minutes looking, does `matchicons.lua` have to require `dirx` to work, `matchicons.lua` and https://github.com/chrisant996/clink-gizmos/issues/3 don't have this info both. the available options of functions from `dirx` is way more than the default cmd dir, is it able to work with the default dir 

`vscode_shell_integration.lua`
installed `clink-gizmos` it comes with `vscode_shell_integration.lua` enabled.
vscode does have shell_integration related things, is it necessary to have `vscode_shell_integration.lua` to work with vscode

**Comment by chrisant996** [comment]
They're unrelated to each other.

Matchicons.lua adds icons to completions in Clink.

Dirx is an unrelated program that's a replacement for the `dir` command, and dirx happens to be able to show icons. 

If you want fzf to show icons, then you need dirx or eza (which I'm pretty sure I documented explicitly, and included directions for setting up fzf to use dirx for icons).

**Comment by NewUserHa** [comment]
those are two questions.

Matchicons.lua itself didn't mention any about dirx, while fzf.lua is the one did. usually, like Terminal-Icons module for powershell, it is able to display icons for files for `ls` command automatically. while Matchicons.lua itself didn't mention any about usage, so this issue is opened.

for the other one 
vscode_shell_integration.lua it only mentioned `Automatically enables shell integration for VSCode embedded terminal windows.` in its documentation 

it would be good if there is some explanation for new comers

**Comment by chrisant996** [comment]
> usually, like Terminal-Icons module for powershell, it is able to display icons for files for `ls` command automatically.

CMD and Powershell are vastly different.  Don't try to compare them like that.


> while Matchicons.lua itself didn't mention any about usage, so this issue is opened.

Matchicons.lua docs say what it does.
I'm not going to even try to document all the things it doesn't do.

> for the other one 
> vscode_shell_integration.lua it only mentioned `Automatically enables shell integration for VSCode embedded terminal windows.` in its documentation 
> 
> it would be good if there is some explanation for new comers 

I recommend to refer to the VSCode documentation to learn about VSCode's shell integration feature. 

I'm not going to spend my personal time documenting answers to all kinds of questions people could potentially ask.  Especially when they can answer the questions themselves with an Internet search.

If you would like to spend your time that way, I am happy to review a PR that you submit with suggested documentation changes.

I recognize that reading documentation and doing searches in a second language can be difficult and time consuming.  But that's not a problem I'm able to invest time in solving.
