### ISSUE TITLE
[Feature] Allow z_popup_dir to work with zoxide

### ISSUE THREAD

**Issue by eblis** [chrisant996/clink-gizmos#8]
It would be nice if the z_popup_dir worked with [zoxide](https://github.com/ajeetdsouza/zoxide) as well as z.

I'm currently using [zoxide](https://github.com/ajeetdsouza/zoxide) plus [clink script](https://github.com/shunsambongi/clink-zoxide) which works nicely, I also have fzf working for it, but the z_popup_dir doesn't seem to work with it.

I tried to force the script to work with zoxide but looks like zoxide's `z` command doesn't have the `-l` parameter.

**Comment by chrisant996** [comment]
`z` and `zoxide` are different, so the same script/command can't really work for both.

Obviously though, it's trivial to change `-l` to `query --list`.

**Comment by eblis** [comment]
Thanks for quickly looking into it.
It's showing the folder list, but on selection it doesn't change the folder.

Created a [small pull request](https://github.com/chrisant996/clink-gizmos/pull/10) to fix this, at least for me.

**Comment by chrisant996** [comment]
Ah, yes, thanks!
